services:
  web:
    build: .
    depends_on:
      - db
    command: gunicorn mlb_stats_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5433
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    command: -p 5433